package com.project.persistence.entity;
// Generated 08/12/2015 06:24:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Advisor generated by hbm2java
 */
@Entity
@Table(name = "advisor")
public class Advisor implements java.io.Serializable {

	private String SId;
	private Instructor instructor;
	private Student student;

	public Advisor() {
	}

	public Advisor(Student student) {
		this.student = student;
	}

	public Advisor(Instructor instructor, Student student) {
		this.instructor = instructor;
		this.student = student;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "student") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "s_ID", unique = true, nullable = false, length = 5)
	public String getSId() {
		return this.SId;
	}

	public void setSId(String SId) {
		this.SId = SId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "i_ID")
	public Instructor getInstructor() {
		return this.instructor;
	}

	public void setInstructor(Instructor instructor) {
		this.instructor = instructor;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
