package com.project.persistence.entity;
// Generated 08/12/2015 06:24:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name = "classroom")
public class Classroom implements java.io.Serializable {

	private ClassroomId id;
	private Short capacity;

	public Classroom() {
	}

	public Classroom(ClassroomId id) {
		this.id = id;
	}

	public Classroom(ClassroomId id, Short capacity) {
		this.id = id;
		this.capacity = capacity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "building", column = @Column(name = "building", nullable = false, length = 15) ),
			@AttributeOverride(name = "roomNumber", column = @Column(name = "room_number", nullable = false, length = 7) ) })
	public ClassroomId getId() {
		return this.id;
	}

	public void setId(ClassroomId id) {
		this.id = id;
	}

	@Column(name = "capacity", precision = 4, scale = 0)
	public Short getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Short capacity) {
		this.capacity = capacity;
	}

}
