package com.project.persistence.entity;
// Generated 08/12/2015 06:24:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "proyecto")
public class Department implements java.io.Serializable {

	private String deptName;
	private String building;
	private BigDecimal budget;
	private Set<Instructor> instructors = new HashSet<Instructor>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Course> courses = new HashSet<Course>(0);

	public Department() {
	}

	public Department(String deptName) {
		this.deptName = deptName;
	}

	public Department(String deptName, String building, BigDecimal budget, Set<Instructor> instructors,
			Set<Student> students, Set<Course> courses) {
		this.deptName = deptName;
		this.building = building;
		this.budget = budget;
		this.instructors = instructors;
		this.students = students;
		this.courses = courses;
	}

	@Id

	@Column(name = "dept_name", unique = true, nullable = false, length = 20)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "building", length = 15)
	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	@Column(name = "budget", precision = 12)
	public BigDecimal getBudget() {
		return this.budget;
	}

	public void setBudget(BigDecimal budget) {
		this.budget = budget;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Instructor> getInstructors() {
		return this.instructors;
	}

	public void setInstructors(Set<Instructor> instructors) {
		this.instructors = instructors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
