package com.project.persistence.entity;
// Generated 12/12/2015 12:27:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrereqId generated by hbm2java
 */
@Embeddable
public class PrereqId implements java.io.Serializable {

	private String courseId;
	private String prereqId;

	public PrereqId() {
	}

	public PrereqId(String courseId, String prereqId) {
		this.courseId = courseId;
		this.prereqId = prereqId;
	}

	@Column(name = "course_id", nullable = false, length = 8)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Column(name = "prereq_id", nullable = false, length = 8)
	public String getPrereqId() {
		return this.prereqId;
	}

	public void setPrereqId(String prereqId) {
		this.prereqId = prereqId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrereqId))
			return false;
		PrereqId castOther = (PrereqId) other;

		return ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
				&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getPrereqId() == castOther.getPrereqId()) || (this.getPrereqId() != null
						&& castOther.getPrereqId() != null && this.getPrereqId().equals(castOther.getPrereqId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getPrereqId() == null ? 0 : this.getPrereqId().hashCode());
		return result;
	}

}
