package com.project.persistence.entity;
// Generated 12/12/2015 12:27:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Prereq generated by hbm2java
 */
@Entity
@Table(name = "prereq")
public class Prereq implements java.io.Serializable {

	private PrereqId id;

	public Prereq() {
	}

	public Prereq(PrereqId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "courseId", column = @Column(name = "course_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "prereqId", column = @Column(name = "prereq_id", nullable = false, length = 8) ) })
	public PrereqId getId() {
		return this.id;
	}

	public void setId(PrereqId id) {
		this.id = id;
	}

}
