package com.project.persistence.entity;
// Generated 08/12/2015 06:24:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "proyecto")
public class Section implements java.io.Serializable {

	private SectionId id;
	private Course course;
	private Classroom classroom;
	private String timeSlotId;
	private Set<Takes> takeses = new HashSet<Takes>(0);

	public Section() {
	}

	public Section(SectionId id, Course course) {
		this.id = id;
		this.course = course;
	}

	public Section(SectionId id, Course course, Classroom classroom, String timeSlotId,
			Set<Takes> takeses) {
		this.id = id;
		this.course = course;
		this.classroom = classroom;
		this.timeSlotId = timeSlotId;
		this.takeses = takeses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "courseId", column = @Column(name = "course_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "secId", column = @Column(name = "sec_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "semester", column = @Column(name = "semester", nullable = false, length = 6) ),
			@AttributeOverride(name = "year", column = @Column(name = "year", nullable = false, precision = 4, scale = 0) ) })
	public SectionId getId() {
		return this.id;
	}

	public void setId(SectionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false, insertable = false, updatable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "building", referencedColumnName = "building"),
			@JoinColumn(name = "room_number", referencedColumnName = "room_number") })
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@Column(name = "time_slot_id", length = 4)
	public String getTimeSlotId() {
		return this.timeSlotId;
	}

	public void setTimeSlotId(String timeSlotId) {
		this.timeSlotId = timeSlotId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "section")
	public Set<Takes> getTakeses() {
		return this.takeses;
	}

	public void setTakeses(Set<Takes> takeses) {
		this.takeses = takeses;
	}

}
