package com.project.persistence.entity;
// Generated 12/12/2015 12:27:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Teaches generated by hbm2java
 */
@Entity
@Table(name = "teaches")
public class Teaches implements java.io.Serializable {

	private TeachesId id;

	public Teaches() {
	}

	public Teaches(TeachesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 5) ),
			@AttributeOverride(name = "courseId", column = @Column(name = "course_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "secId", column = @Column(name = "sec_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "semester", column = @Column(name = "semester", nullable = false, length = 6) ),
			@AttributeOverride(name = "year", column = @Column(name = "year", nullable = false, precision = 4, scale = 0) ) })
	public TeachesId getId() {
		return this.id;
	}

	public void setId(TeachesId id) {
		this.id = id;
	}

}
