package com.project.persistence.entity;
// Generated 08/12/2015 06:24:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TimeSlot generated by hbm2java
 */
@Entity
@Table(name = "time_slot")
public class TimeSlot implements java.io.Serializable {

	private TimeSlotId id;
	private Byte endHr;
	private Byte endMin;

	public TimeSlot() {
	}

	public TimeSlot(TimeSlotId id) {
		this.id = id;
	}

	public TimeSlot(TimeSlotId id, Byte endHr, Byte endMin) {
		this.id = id;
		this.endHr = endHr;
		this.endMin = endMin;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "timeSlotId", column = @Column(name = "time_slot_id", nullable = false, length = 4) ),
			@AttributeOverride(name = "day", column = @Column(name = "day", nullable = false, length = 1) ),
			@AttributeOverride(name = "startHr", column = @Column(name = "start_hr", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "startMin", column = @Column(name = "start_min", nullable = false, precision = 2, scale = 0) ) })
	public TimeSlotId getId() {
		return this.id;
	}

	public void setId(TimeSlotId id) {
		this.id = id;
	}

	@Column(name = "end_hr", precision = 2, scale = 0)
	public Byte getEndHr() {
		return this.endHr;
	}

	public void setEndHr(Byte endHr) {
		this.endHr = endHr;
	}

	@Column(name = "end_min", precision = 2, scale = 0)
	public Byte getEndMin() {
		return this.endMin;
	}

	public void setEndMin(Byte endMin) {
		this.endMin = endMin;
	}

}
